name: Commitlint

on:
  push:
    branches-ignore:
      - "main"  # 排除 main 分支的 push 事件
  pull_request:
    branches-ignore:
      - "main"  # 排除 main 分支的 pull_request 事件
  workflow_dispatch:  # 允许手动触发工作流程

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 使用最新版本的 checkout 动作

      - name: Set up Node.js
        uses: actions/setup-node@v4  # 使用最新版本的 setup-node 动作
        with:
          node-version: '20'  # 显式指定 Node.js 版本

      - name: Install Dependencies
        run: |
          npm ci
          npm install @commitlint/cli @commitlint/config-conventional

      - name: Configure Commitlint
        run: |
          # 确保 .commitlintrc.js 存在
          touch .commitlintrc.js
          echo "module.exports = {extends: ['@commitlint/config-conventional']};"> .commitlintrc.js

      - name: Check Commits
        run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          else
            npx commitlint --from $(git rev-list --max-parents=0 HEAD) --to HEAD --verbose
          fi