ci(go): add gofmt check on Windows for code formatting

Configured a CI workflow to run gofmt on the 'my-ci-branch' branch for both push and pull request events.
Switched the workflow to run on the 'windows-latest' environment. This ensures Go code formatting is checked on a Windows-based system using gofmt.
