name: Go Format Check

on:
  push:
    branches:
      - my-ci-branch
  pull_request:
    branches:
      - my-ci-branch

jobs:
  gofmt-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Run gofmt to check formatting
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "Go code is not properly formatted."
          exit 1
        else
          echo "Go code is properly formatted."
        fi

