name: Go Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gofmt-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run gofmt to check formatting
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "Go code is not properly formatted:"
            echo "$unformatted"
            exit 1
          else
            echo "Go code is properly formatted."
          fi
