name: TechMojotvGo
on: push
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.23.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.23.1
        id: go

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        run: go build .

      - name: Test
        run: go test -v .
